/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as BudgetsRouteImport } from './routes/budgets'
import { Route as GoalsRouteImport } from './routes/goals'
import { Route as ImportsRouteRouteImport } from './routes/imports/route'
import { Route as InvestmentsRouteImport } from './routes/investments'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as ImportsIndexRouteImport } from './routes/imports/index'
import { Route as ImportsJobIdRouteImport } from './routes/imports/$jobId'
import { Route as ImportsNewRouteImport } from './routes/imports/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetsRoute = BudgetsRouteImport.update({
  id: '/budgets',
  path: '/budgets',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsRoute = GoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportsRouteRoute = ImportsRouteRouteImport.update({
  id: '/imports',
  path: '/imports',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestmentsRoute = InvestmentsRouteImport.update({
  id: '/investments',
  path: '/investments',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportsIndexRoute = ImportsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ImportsRouteRoute,
} as any)
const ImportsJobIdRoute = ImportsJobIdRouteImport.update({
  id: '/$jobId',
  path: '/$jobId',
  getParentRoute: () => ImportsRouteRoute,
} as any)
const ImportsNewRoute = ImportsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ImportsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/imports': typeof ImportsRouteRouteWithChildren
  '/accounts': typeof AccountsRoute
  '/assistant': typeof AssistantRoute
  '/budgets': typeof BudgetsRoute
  '/goals': typeof GoalsRoute
  '/investments': typeof InvestmentsRoute
  '/login': typeof LoginRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/timeline': typeof TimelineRoute
  '/transactions': typeof TransactionsRoute
  '/imports/$jobId': typeof ImportsJobIdRoute
  '/imports/new': typeof ImportsNewRoute
  '/imports/': typeof ImportsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/assistant': typeof AssistantRoute
  '/budgets': typeof BudgetsRoute
  '/goals': typeof GoalsRoute
  '/investments': typeof InvestmentsRoute
  '/login': typeof LoginRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/timeline': typeof TimelineRoute
  '/transactions': typeof TransactionsRoute
  '/imports/$jobId': typeof ImportsJobIdRoute
  '/imports/new': typeof ImportsNewRoute
  '/imports': typeof ImportsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/imports': typeof ImportsRouteRouteWithChildren
  '/accounts': typeof AccountsRoute
  '/assistant': typeof AssistantRoute
  '/budgets': typeof BudgetsRoute
  '/goals': typeof GoalsRoute
  '/investments': typeof InvestmentsRoute
  '/login': typeof LoginRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/timeline': typeof TimelineRoute
  '/transactions': typeof TransactionsRoute
  '/imports/$jobId': typeof ImportsJobIdRoute
  '/imports/new': typeof ImportsNewRoute
  '/imports/': typeof ImportsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/imports'
    | '/accounts'
    | '/assistant'
    | '/budgets'
    | '/goals'
    | '/investments'
    | '/login'
    | '/reports'
    | '/settings'
    | '/timeline'
    | '/transactions'
    | '/imports/$jobId'
    | '/imports/new'
    | '/imports/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts'
    | '/assistant'
    | '/budgets'
    | '/goals'
    | '/investments'
    | '/login'
    | '/reports'
    | '/settings'
    | '/timeline'
    | '/transactions'
    | '/imports/$jobId'
    | '/imports/new'
    | '/imports'
  id:
    | '__root__'
    | '/'
    | '/imports'
    | '/accounts'
    | '/assistant'
    | '/budgets'
    | '/goals'
    | '/investments'
    | '/login'
    | '/reports'
    | '/settings'
    | '/timeline'
    | '/transactions'
    | '/imports/$jobId'
    | '/imports/new'
    | '/imports/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ImportsRouteRoute: typeof ImportsRouteRouteWithChildren
  AccountsRoute: typeof AccountsRoute
  AssistantRoute: typeof AssistantRoute
  BudgetsRoute: typeof BudgetsRoute
  GoalsRoute: typeof GoalsRoute
  InvestmentsRoute: typeof InvestmentsRoute
  LoginRoute: typeof LoginRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  TimelineRoute: typeof TimelineRoute
  TransactionsRoute: typeof TransactionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budgets': {
      id: '/budgets'
      path: '/budgets'
      fullPath: '/budgets'
      preLoaderRoute: typeof BudgetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals': {
      id: '/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof GoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imports': {
      id: '/imports'
      path: '/imports'
      fullPath: '/imports'
      preLoaderRoute: typeof ImportsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investments': {
      id: '/investments'
      path: '/investments'
      fullPath: '/investments'
      preLoaderRoute: typeof InvestmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imports/': {
      id: '/imports/'
      path: '/'
      fullPath: '/imports/'
      preLoaderRoute: typeof ImportsIndexRouteImport
      parentRoute: typeof ImportsRouteRoute
    }
    '/imports/$jobId': {
      id: '/imports/$jobId'
      path: '/$jobId'
      fullPath: '/imports/$jobId'
      preLoaderRoute: typeof ImportsJobIdRouteImport
      parentRoute: typeof ImportsRouteRoute
    }
    '/imports/new': {
      id: '/imports/new'
      path: '/new'
      fullPath: '/imports/new'
      preLoaderRoute: typeof ImportsNewRouteImport
      parentRoute: typeof ImportsRouteRoute
    }
  }
}

interface ImportsRouteRouteChildren {
  ImportsJobIdRoute: typeof ImportsJobIdRoute
  ImportsNewRoute: typeof ImportsNewRoute
  ImportsIndexRoute: typeof ImportsIndexRoute
}

const ImportsRouteRouteChildren: ImportsRouteRouteChildren = {
  ImportsJobIdRoute: ImportsJobIdRoute,
  ImportsNewRoute: ImportsNewRoute,
  ImportsIndexRoute: ImportsIndexRoute,
}

const ImportsRouteRouteWithChildren = ImportsRouteRoute._addFileChildren(
  ImportsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ImportsRouteRoute: ImportsRouteRouteWithChildren,
  AccountsRoute: AccountsRoute,
  AssistantRoute: AssistantRoute,
  BudgetsRoute: BudgetsRoute,
  GoalsRoute: GoalsRoute,
  InvestmentsRoute: InvestmentsRoute,
  LoginRoute: LoginRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  TimelineRoute: TimelineRoute,
  TransactionsRoute: TransactionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
